name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/moveaxlab/godror-devcontainer:latest
    steps:

    - name: Check out code into the Go module directory
      uses: actions/checkout@v4

    - name: Get dependencies
      run: go get -v -t -d ./...

    - name: Build
      run: go build -v .

    - name: Check
      run: go run ./check

    - name: Test
      continue-on-error: true
      run: go test
